version: "3.7"

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    networks:
      - rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    healthcheck:
      test: rabbitmq-diagnostics check_running

  file_uploader:
    build:
      context: file_uploader
    container_name: file_uploader
    image: file_uploader:latest
    networks:
      - rabbit
    restart: on-failure
    volumes:
      - type: bind
        source: ${PWD}/file_uploader/files_to_upload
        target: /tmp/observed

  sanitizer:
    build:
      context: sanitizer
    container_name: sanitizer
    image: sanitizer:latest
    networks:
      - rabbit
    restart: on-failure

networks:
  rabbit:
    attachable: true
