version: "3.9"

services:

  deeppavlov:
    env_file:
      - ./annotators/deeppavlov/.env
    image: smdrm/annotators/deeppavlov
    hostname: deeppavlov
    networks:
      - annotators
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - "deeppavlov:/opt/deeppavlov/.deeppavlov"

  floods:
    env_file:
      - ./annotators/floods/.env
    image: smdrm/annotators/floods
    hostname: floods
    networks:
      - annotators
    ports:
      - "5010:5000"
    restart: on-failure
    volumes:
      - "floods:/opt/floods/models"

networks:
  annotators:
    attachable: true

volumes:
  deeppavlov:
  floods:

