version: "3.7"

services:

  fires:
    command:
      - "--port=15002"
    container_name: fires-test
    networks:
      - tests
    ports:
      - "15002:15002"
    restart: on-failure
    volumes:
      - "${PWD}/annotators/fires/models:/app/models"

  floods:
    command:
      - "--port=15001"
    container_name: floods-test
    networks:
      - tests
    ports:
      - "15001:15001"
    restart: on-failure
    volumes:
      - "${PWD}/annotators/floods/models:/app/models"

networks:
  tests:
    attachable: true
