version: "3.7"

services:

  upload:
    build:
      context: upload
    image: uploadapi:latest

  engine:
    build:
      context: engine
    image: engineapi:latest

  text-normalize:
    build:
      context: transformers/text_normalize
    image: textnormalizeapi:latest

  fires:
    build:
      context: annotators/fires
    image: firesapi:latest

  floods:
    build:
      context: annotators/floods
    image: floodsapi:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
