version: "3.7"

services:

  engine:
    build:
      context: engine
      target: builder
    container_name: engine
    env_file:
      - "${PWD}/engine/.env"
    image: engine:latest
    networks:
      - ml
      - elastic
    ports:
      - "5555:5555"
    restart: always
    volumes:
      - "${PWD}/engine/uploads:/engine/uploads" # path observed for new uploads

  floods:
    build:
      context: annotators/floods
      target: builder
    container_name: floods
    env_file:
      - "${PWD}/annotators/floods/.env"
    healthcheck:
      test: python -c '''import requests; requests.get("http://localhost:5001").status_code == 200'''
      interval: 30s
      timeout: 5s
      retries: 3
    image: floodsapi:latest
    networks:
      - ml
    ports:
      - "5001:5001"
    restart: on-failure
    volumes:
      - "${PWD}/annotators/floods/models:/floods/models"

  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - "es_node:/usr/share/elasticsearch/data"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - elastic
    ports:
      - "5601:5601"

volumes:
  es_node:
  engine_logs:

networks:
  ml:
    attachable: true
  elastic:
    driver: bridge
