version: "3.9"

services:

  floods:
    command:
      - "--port=15001"
    container_name: floods-test
    networks:
      - tests
    ports:
      - "15001:15001"
    restart: on-failure
    volumes:
      - "floods:/opt/floods/models"

networks:
  tests:
    attachable: true

volumes:
  floods:
