version: "3.7"

services:

  engine:
    build:
      context: engine
      target: builder
    container_name: engine
    env_file:
      - engine/.env
    healthcheck:
      test: python -c '''import requests; requests.get("http://localhost:5555").status_code == 200'''
      interval: 10s
      timeout: 10s
      retries: 3
    image: engine:latest
    networks:
      - backend
      - elastic
    ports:
      - "5555:5555"
    restart: always
    volumes:
      - type: bind
        source: ${PWD}/engine/data
        target: /engine/data

  floods:
    build:
      context: annotators/floods
      target: builder
    container_name: floods
    healthcheck:
      test: python -c '''import requests; requests.get("http://localhost:5001").status_code == 200'''
      interval: 10s
      timeout: 10s
      retries: 3
    image: floodsapi:latest
    networks:
      - backend
    ports:
      - "5001:5001"
    restart: on-failure
    volumes:
      - type: bind
        source: ${PWD}/annotators/floods/models
        target: /floods/models

  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - es_node:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - elastic
    ports:
      - "5601:5601"

volumes:
  es_node:
  disaster_db:

networks:
  backend:
    attachable: true
  elastic:
    driver: bridge
