version: "3.9"

services:

  deeppavlov-gpu:
    # official docker hub deeppavlov image
    # https://hub.docker.com/r/deeppavlov/base-gpu
    image: deeppavlov/base-gpu:0.15.0

  deeppavlov-cpu:
    # official docker hub deeppavlov image
    # https://hub.docker.com/r/deeppavlov/base-cpu
    image: deeppavlov/base-cpu:0.15.0
    #build: ./annotators/deeppavlov/
    #image: jrc/deeppavlov:0.1.0

  floods:
    build: ./annotators/floods/
    image: jrc/floods_base
