name: Airflow CI

on:
  push:
    paths:
      - 'airflow/**/*.py'

jobs:
  airflow-ci:
    name: Airflow unittests
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
  
    - name: Build Docker image
      run: |
          echo -e "AIRFLOW_UID=$(id -u)" > .env
          docker-compose up --build airflow-init

    - name: Run unittests
      run: docker-compose run --rm airflow-worker bash -c pytest

