name: Airflow CI

on:
  push:
    paths:
      - 'airflow/**/*.py'

jobs:
  airflow-ci:
    name: Airflow unittests
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
  
    - name: Build Docker image
      run: docker build ./airflow --tag airflow:test

    - name: Run unittests
      run: docker container run --rm airflow:test pytest

