name: Annotate Tweets task CI

on:
  push:
    paths:
      - 'tasks/annotate_tweets/**/*.py'

jobs:
  annotate-tweets-ci:
    name: Annotate Tweets unittests
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
  
    - name: Build Docker images
      run: |
          # build base image
          docker build ./libdrm --tag libdrm
          docker build ./tasks/annotate_tweets --tag annotate-tweets

    - name: Run unittests
      run: docker container run --rm annotate-tweets pytest

