name: Cache Tweets task CI

on:
  push:
    paths:
      - 'tasks/cache_tweets/**/*.py'

jobs:
  cache-tweets-ci:
    name: Cache Tweets unittests
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
  
    - name: Build Docker images
      run: |
          # build base image
          docker build ./libdrm --tag libdrm
          docker build ./tasks/cache_tweets --tag cache-tweets

    - name: Run unittests
      run: docker container run --rm cache-tweets pytest

