name: SMDRM CI

on:
  push:
    # trigger every time we push a python file to libdrm
    paths:
      - 'libdrm/**.py'

jobs:
  libdrm:
    name: Build, test, and publish LIBDRM Python package

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install build pytest
        pip install libdrm/

    - name: Test with pytest
      run: pytest libdrm/tests

    - name: Build binary package
      run: python -m build --sdist --outdir dist/ libdrm

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

  smdrm-ci:
    name: SMDRM Integration Tests
    needs: libdrm-ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Integration tests for Upload API
      run: |
        # init Upload API test instances and run integration tests
        docker-compose -f ./upload/docker-compose.test.yml up --build --exit-code-from tester
