name: Extract Tweets task CI

on:
  push:
    paths:
      - 'extract_tweets/**/*.py'

jobs:
  extract-tweets-ci:
    name: Extract Tweets unittests
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
  
    - name: Build Docker images
      run: |
          # build base image
          docker build ./libdrm --tag libdrm
          docker build ./extract_tweets --tag extract-tweets

    - name: Run unittests
      run: docker container run --rm extract-tweets pytest

