name: LIBDRM CI

on:
  push:
    paths:
      - 'libdrm/**/*.py'

jobs:
  libdrm-ci:
    name: LibDRM unittests
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2
  
    - name: Build Docker image
      run: docker build ./libdrm --tag libdrm:test

    - name: Run unittests
      run: docker container run --rm libdrm:test pytest

