name: LIBDRM Tests

on: push

jobs:
  build-n-test:
    name: Build and Test LIBDRM Python Package
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        # upgrade and install test deps
        python3 -m pip install --upgrade pip pytest
        # install package locally for testing purposes
        python3 -m pip install libdrm/

    - name: Run LIBDRM Unit tests
      run: python3 -m pytest -v libdrm/tests

    - name: Run Upload API Integration tests
      run: |
        # init Upload API test instances and run integration tests
        docker-compose -f ./upload/docker-compose.test.yml up --build --exit-code-from tester
        # clean up
        docker-compose -f ./upload/docker-compose.test.yml down
